### ISSUE TITLE
Doesn't seem to register HDF5 1.14.2 as a version.

### ISSUE THREAD

**Issue by trippalamb** [aldanor/hdf5-rust#257]
Had to roll back to 1.10.10 in order for hdf5-sys to register a version of HDF5 during the cargo build process.

**Comment by mulimoen** [comment]
Do you have the version string? In #243 I saw and implemented support for strings like `1.14.1.2`

**Comment by TrippLamb** [comment]
I'm sorry. I don't understand what that means.

**Comment by mulimoen** [comment]
If you look in the `H5pubconf.h` header of the install, what is the value of `H5_VERSION`?

**Comment by trippalamb** [comment]
It is the same as this issue title "1.14.2"

```cpp
/* Version number of package */
#define H5_VERSION "1.14.2"
```

**Comment by wbthomason** [comment]
I'm also hitting this issue - is it correct that `hdf5-rs` is currently incompatible with HDF5 1.14.2?

**Comment by loenard97** [comment]
I'm having the same problem. On Arch linux 6.5.8 with the latest hdf5 1.14.2-1 package installed, cargo fails when building a project with hdf5 0.8.1 as a dependency. `cargo build` ends with the following error:

```
  Found HDF5 pkg-config entry
      Include paths:
      - "/usr/include"
      Link paths:
      - "/usr/lib"
  Located HDF5 headers at:
      "/usr/include"
  Parsing HDF5 config from:
      "/usr/include/H5pubconf.h"

  --- stderr
  thread 'main' panicked at /home/dennis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hdf5-sys-0.8.1/build.rs:200:21:
  Invalid H5_VERSION: "1.14.2"
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
     1: core::panicking::panic_fmt
               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
     2: build_script_build::Header::parse
     3: build_script_build::LibrarySearcher::finalize
     4: build_script_build::main
     5: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

My `/usr/include/H5pubconf.h` header also reports version 1.14.2, same as @trippalamb:
```c
/* Version number of package */
#define H5_VERSION "1.14.2"
```

**Comment by mulimoen** [comment]
Are you using the version from `crates.io` or using the`master` branch from here?

**Comment by loenard97** [comment]
@nleroy917  try to set the hdf5 dependency to the git repo in your `Cargo.toml`. That did it for me.
```toml
[dependencies]
hdf5 = { git = "https://github.com/aldanor/hdf5-rust.git" }
```

**Comment by nleroy917** [comment]
I *just* saw your comment above. Thank you, I will try this. I'm actually getting this build error in **someone elses** project, so I need to do a clone, change the `Cargo.toml`, then try a custom build... will report back...

**Comment by mulimoen** [comment]
@nleroy917 Is it possible to add an override? https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html

**Comment by nleroy917** [comment]
😱 That worked super well. Even better since `hdf5` was going to be a dependency of a dependency. I've got another problem now about not having a threadsafe version of hdf5 installed, but I think that one is unrelated to this issue 😅

**Comment by mulimoen** [comment]
Could be easier to use the static version of `hdf5`, try enabling the `static` feature (still only in `master`).

**Comment by nleroy917** [comment]
Oh, it looks like its actually an issue with `hdf5-sys`:

```
thread 'main' panicked at ~/.cargo/git/checkouts/hdf5-rust-c1072d7a2617f7d8/26046fb/hdf5-sys/build.rs:697:17:
        Enabled feature "threadsafe" but the HDF5 library was not built with HDF5_ENABLE_THREADSAFE
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
      error: `cargo rustc --lib --message-format=json-render-diagnostics --manifest-path Cargo.toml --release -v --features pyo3/extension-module --crate-type cdylib -- -C 'link-args=-undefined dynamic_lookup -Wl,-install_name,@rpath/_snapatac2.cpython-311-darwin.so'` failed with code 101
```

Interestingly, I don't even have `threadsage` set:
```toml
[patch.crates-io]
hdf5 = { git = "https://github.com/aldanor/hdf5-rust.git" }
hdf5-sys = { git = "https://github.com/aldanor/hdf5-rust.git", features = ["static", "zlib"]}
```

**Comment by TrippLamb** [comment]
> @nleroy917 try to set the hdf5 dependency to the git repo in your `Cargo.toml`. That did it for me.
> 
> ```toml
> [dependencies]
> hdf5 = { git = "https://github.com/aldanor/hdf5-rust.git" }
> ```

If I do this, it breaks my dependency on hdf5-sys. Is there a way to adjust for this? I'm reasonably new to rust and don't have a great grasp on the way the cargo works.

**Comment by mulimoen** [comment]
@trippalamb Add another line with `hdf5-sys` and the same contents

**Comment by TrippLamb** [comment]
That did indeed seem to fix it. I appreciate it.

**Comment by nleroy917** [comment]
I was able to solve my problem by just `unset`-ing my `HDF5_DIR` variable. I have it in my `.zshrc` since I need it so often, but this time it was causing problems I guess.
